### ISSUE TITLE
Parquet support

### ISSUE THREAD

**Issue by matteobe** [uzh-dqbm-cmi/data-traffic-control#12]
I tried running datatc for saving in parquet and noticed that it requires either:
- pyarrow
- fastparquet

But they are not in the datatc package requirements.

**Comment by lokijuhy** [comment]
I made that decision intentionally, because that’s how I saw it was done in pandas. By default, pandas doesn’t install pyarrow/fastparquet. When you run `pd.read_parquet` for the first time, it gives an error message instructing you to install one of them. I assume this is to reduce the memory footprint of the pandas package install. 

I forget exactly, but I’m assuming I didn’t make datatc give a nice error message instructing to install pyarrow/fastparquet…? Would doing that satisfy your issue?

**Comment by matteobe** [comment]
Maybe you can have a section in the docs for the supported file formats... and necessary packages for using them with datatc  think would be more helpful..
I was looking in the docs and didn't find it, then I crawled through the code to see which file types are supported...

**Comment by lokijuhy** [comment]
That is an excellent point. I added this task to my backlog.
