### ISSUE TITLE
Saving file name confusion.

### ISSUE THREAD

**Issue by daniel-trejobanos** [uzh-dqbm-cmi/data-traffic-control#18]
Hi, I have a couple of comments about the saving filename format

I saved a SelfAwareData object after applying a transformation.

`
x_train_ss = x_train.transform(ct.chunk_sum_stats)
 x_train_ss.save('/opt/data/pipeline_test/sstats_train.parquet')
`
The output  is
`created new file /opt/data/pipeline_test/sad_dir__2021-01-13_10-44-04__26f865b__sstats_train`
and effectively the created file is

`created new file /opt/data/pipeline_test/sad_dir__2021-01-13_10-44-04__26f865b__sstats_train`

I have a couple of comments:

- The sad_dir prefix is unnecessary
- the parquet extension is not preserved.

**Comment by lokijuhy** [comment]
I have reasons for both of these things, so please help me figure out how to make it more intuitive as a user.

When a `SelfAwareData` object is saved, it creates not a single file but a _directory_ containing a set of files. Inside the `/opt/data/pipeline_test/sad_dir__2021-01-13_10-44-04__26f865b__sstats_train` directory, you will find:
 * `data.parquet`: your data file
 * `code.txt`: a plain text file showing the code of the transform function
 * `func.dill`: a serialized copy of the transform function that is reusable
 
I decided to implement saving `SelfAwareData` via multiple files like this so that each component- the data, the transform code- is readable even if you are not using `SelfAwareData`. If `SelfAwareData` saves to its own file format (like `sstats_train.sad`), then your collaborators also _have_ to use `SelfAwareData` to read your files. This way, other people can still read your files, although it is certainly more awkward.

When you view and navigate the filesystem with `DataManager`, `SelfAwareData` directories  "look" like normal files. If you open up `DataManger` and do an `.ls()`, this `SelfAwareData` directory will display as `sstats_train.parquet`. But on the actual filesystem, it is more complicated. This is a downside of using `SelfAwareData` without `DataManager` like we discussed. 

So:
* the sad_dir prefix is there to indicate to DataManager that this is a `SelfAwareDataDirectory`, so that `DataManager` treats it differently than a normal directory
* the parquet extension is not preserved in the name because it is a directory, and does not have a file extension. The file extension is preserved in the `data.parquet` file inside the directory.

Please let me know how you think I could make this more intuitive. Maybe I could change the save message to `created new SelfAwareData directory at /opt/data/pipeline_test/sad_dir__2021-01-13_10-44-04__26f865b__sstats_train`?

**Comment by daniel-trejobanos** [comment]
Hi, thank you very much that clears things a lot, It also clears confusions I had with  DataManager. I think the new message you suggest is better.
